#!/bin/bash

# Load other bashrc files if present. (Use compgen so we don't run ls on
# literal glob when no files match, which can break in non-interactive/Cursor.)
if compgen -G "$HOME/.bashrc_*" >/dev/null 2>&1; then
  for f in $(compgen -G "$HOME/.bashrc_*" | sort); do [[ -f "$f" ]] && source "$f"; done
fi

# For now, I really don't want to try and think to hard about whether
# to put things in bashrc vs bash_profile, so I'm just going to have 
# the bashrc read the bash_profile.
[ -f $HOME/.bash_profile ] && . $HOME/.bash_profile


[ -d "$HOME/.sc-tools" ] && source "$HOME/.sc-tools/dotfiles/env.bash" #sc-tools-setup
