#!/bin/bash

export HISTSIZE=100000

# Global stuff
export PATH=$HOME/bin:$PATH
export EDITOR=vi

# Homebrew stuff
export PATH=$HOME/homebrew/bin:$PATH
export LD_LIBRARY_PATH=$HOME/homebrew/lib:$LD_LIBRARY_PATH

# Exclude files and folders that start with "." -- Useful when listing files but
# you don't care about the hidden ones especially .git etc.
alias no.='egrep -v "/\\.|^\\.\[^/\]"'

# List and list all, vertically please.
alias la='ls -Glah'
alias ll='ls -Glh'
alias l='ls -Gth'

# ls color settings
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# Given an expanded file pattern, return true if the first one exists.
exists() {
  test -e $1
}

field() {
  s=""; c=""
  for a in $*; do s="$s$c\$$a"; c=","; done
  awk "{ print $s }"
}

# Who wants to type "field" everywhere?  f that!
alias f=field

# Display disk usage, order by folder name (more tree-like)
# requires align, in home/bin
alias dk='du -k | f 2 1 | sort | f 2 1 | align | sed "s/\.\//  /"'

# Reload ~./bash_profile
alias reload="source ~/.bash_profile"

# Load other bash profile files if present.
if exists $HOME/.bash_profile_*
then for f in $(ls $HOME/.bash_profile_* | sort); do source $f; done
fi

export PS1=$GREEN'$(hostname -s) '$CYAN'\w'$RED'$(git_branch_name 1>/dev/null && echo " ($(git_branch_name))")'$YELLOW'\$ '$NO_COLOR

export PATH="$HOME/.cargo/bin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/brendan/miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/brendan/miniconda/etc/profile.d/conda.sh" ]; then
        . "/Users/brendan/miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/Users/brendan/miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
