#!/bin/bash

# Load other bashrc files if present.
if [[ -n `ls ~/.bashrc_* 2> /dev/null` ]]; then
  for f in $(ls $HOME/.bashrc_* | sort); do source $f; done
fi

# For now, I really don't want to try and think to hard about whether
# to put things in bashrc vs bash_profile, so I'm just going to have 
# the bashrc read the bash_profile.
[ -f $HOME/.bash_profile ] && . $HOME/.bash_profile

